"use client";

import React from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import PromptGenerator from '@/components/PromptGenerator';
import PromptImprover from '@/components/PromptImprover';
import PromptVisualizer from '@/components/PromptVisualizer';
import { FloatingFeature } from '@/components/floating-feature';
import { Zap, Lightbulb, Sparkles, Info } from 'lucide-react';
import { useLanguage } from '@/lib/i18n/LanguageContext';
import { FaGithub, FaDiscord, FaXTwitter } from 'react-icons/fa6';
import { SiHuggingface } from 'react-icons/si';

export default function Home() {
  const { t } = useLanguage();

  return (
    <article className="relative min-h-screen overflow-hidden bg-gradient-subtle">
      {/* Decorative elements */}
      <div className="absolute inset-0 bg-noise"></div>

      {/* Background decorations */}
      <div className="absolute top-40 -left-32 w-96 h-96 bg-primary/10 rounded-full filter blur-3xl opacity-20"></div>
      <div className="absolute bottom-0 right-0 w-80 h-80 bg-accent/20 rounded-full filter blur-3xl opacity-20"></div>
      <div className="absolute top-1/4 right-1/4 w-64 h-64 bg-blue-300/10 rounded-full filter blur-3xl opacity-10"></div>
      <div className="absolute bottom-1/3 left-1/4 w-48 h-48 bg-purple-300/10 rounded-full filter blur-3xl opacity-10"></div>

      <div className="container relative mx-auto pt-8 pb-16 px-4 sm:px-6 lg:px-8">
        <header className="text-center mb-14">
          <div className="inline-block mb-3">
            <span className="inline-block py-1 px-3 bg-primary/10 text-primary rounded-full text-sm font-medium mb-4">
              <span className="flex items-center gap-1.5">
                <Zap className="h-3.5 w-3.5" />
                {t('poweredBy')}
              </span>
            </span>
          </div>

          <h1 className="text-4xl font-extrabold tracking-tight lg:text-6xl mb-6">
            <span className="text-gradient">
              {t('title')}
            </span>
          </h1>

          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            {t('subtitle')}
          </p>
        </header>

        <section aria-labelledby="tool-section" className="relative max-w-4xl mx-auto">
          {/* Floating feature card */}
          <FloatingFeature />

          <div className="absolute inset-0 bg-gradient-to-r from-primary/5 to-accent/5 rounded-2xl transform rotate-1 scale-[1.01]"></div>
          <div className="card-stripe relative p-8 sm:p-10">
            <Tabs defaultValue="generate" className="w-full">
              <TabsList className="grid w-full grid-cols-2 mb-10 p-1 gap-1">
                <TabsTrigger value="generate" className="text-large py-3 group">
                  <span className="flex items-center gap-2">
                    <Lightbulb className="h-4 w-4 group-data-[state=active]:text-primary" />
                    {t('generatePrompt')}
                  </span>
                </TabsTrigger>
                <TabsTrigger value="improve" className="text-large py-3 group">
                  <span className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 group-data-[state=active]:text-primary" />
                    {t('improvePrompt')}
                  </span>
                </TabsTrigger>
              </TabsList>
              <TabsContent value="generate" className="pt-2">
                <PromptGenerator />
              </TabsContent>
              <TabsContent value="improve" className="pt-2">
                <PromptImprover />
              </TabsContent>
            </Tabs>
            <div className="border-t pt-4 mt-6">
              <h4 className="font-medium mb-2">Disclaimer</h4>
              <div className="text-xs text-muted-foreground p-3 bg-muted/30 rounded border">
                <p className="whitespace-pre-wrap">
                  Disclaimer: The responses generated by this Artificial Intelligence (AI) system are autonomously constructed and do not necessarily reflect the views or positions of the developing organizations, their affiliates, or any of their employees. These AI-generated responses do not represent those of the organizations. The organizations do not endorse, support, sanction, encourage, verify, or agree with the comments, opinions, or statements generated by this AI. The information produced by this AI is not intended to malign any religion, ethnic group, club, organization, company, individual, anyone, or anything. It is not the intent of the organizations to malign any group or individual. The AI operates based on its programming and training data and its responses should not be interpreted as the explicit intent or opinion of the organizations.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* About Typhoon Section */}
        <section className="max-w-4xl mx-auto mt-20 bg-white/50 p-6 rounded-xl shadow-sm border border-gray-100">
          <h2 className="text-2xl font-bold mb-4">About Typhoon LLM</h2>
          <div className="prose prose-slate max-w-none">
            <p>
              Typhoon is a powerful large language model designed to help developers and businesses create AI-powered applications.
              This tool demonstrates the prompt engineering capabilities of Typhoon, showcasing how it can be used to generate
              and optimize prompts for better AI interactions.
            </p>
            <p className="mt-4">
              <a
                href="https://opentyphoon.ai"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center text-primary font-medium hover:underline"
              >
                <Info className="mr-2 h-4 w-4" />
                Learn more about Typhoon's capabilities
              </a>
            </p>
          </div>
        </section>

        {/* Visualization Section */}
        <section aria-labelledby="visualization-section" className="relative max-w-4xl mx-auto mt-20">
          <PromptVisualizer />
        </section>

        {/* FAQ Section */}
        <section className="max-w-4xl mx-auto mt-20">
          <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
          <div className="space-y-6">
            <div className="bg-white/50 rounded-lg p-6 shadow-sm border border-gray-100">
              <h3 className="text-lg font-medium mb-2">What is Typhoon?</h3>
              <p className="text-gray-600">
                Typhoon is an advanced large language model (LLM) designed to power AI applications,
                with capabilities for prompt engineering, text generation, and more.
              </p>
            </div>
            <div className="bg-white/50 rounded-lg p-6 shadow-sm border border-gray-100">
              <h3 className="text-lg font-medium mb-2">How does the Prompt Optimizer work?</h3>
              <p className="text-gray-600">
                The Prompt Optimizer uses Typhoon's advanced AI algorithms to analyze your task or existing prompt,
                then generates an optimized version designed to produce better results from LLM systems.
              </p>
            </div>
            <div className="bg-white/50 rounded-lg p-6 shadow-sm border border-gray-100">
              <h3 className="text-lg font-medium mb-2">Can I use this tool with other language models?</h3>
              <p className="text-gray-600">
                Yes! While this tool is powered by Typhoon, the optimized prompts it generates can be used with
                any language model to improve your results.
              </p>
            </div>
          </div>
        </section>

        {/* New Footer Section */}
        <footer className="bg-gray-50 py-8 mt-24 border-t border-gray-200">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex flex-col md:flex-row justify-between items-center gap-6">
              {/* Left side: BuiltWithTyphoon and Terms */}
              <div className="flex flex-col sm:flex-row items-center gap-4 text-sm text-gray-500">
                <a
                  href="https://opentyphoon.ai"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-purple-600 hover:text-purple-700 font-semibold transition-colors"
                >
                  #BuiltWithTyphoon
                </a>
                <span className="hidden sm:inline">|</span>
                <a
                  href="https://opentyphoon.ai/tac"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-gray-700 transition-colors"
                >
                  Terms and Conditions
                </a>
              </div>

              {/* Right side: Social Icons */}
              <div className="flex items-center gap-5">
                <a
                  href="https://github.com/scb-10x"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-gray-600 transition-colors"
                  aria-label="GitHub"
                >
                  <FaGithub className="h-5 w-5" />
                </a>
                <a
                  href="https://discord.gg/9F6nrFXyNt"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-gray-600 transition-colors"
                  aria-label="Discord"
                >
                  <FaDiscord className="h-5 w-5" />
                </a>
                <a
                  href="https://huggingface.co/scb10x"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-gray-600 transition-colors"
                  aria-label="Hugging Face"
                >
                  <SiHuggingface className="h-5 w-5" />
                </a>
                <a
                  href="https://x.com/opentyphoon"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-gray-600 transition-colors"
                  aria-label="X (formerly Twitter)"
                >
                  <FaXTwitter className="h-5 w-5" />
                </a>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </article>
  );
}
